[package]
name = "bnn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.16"
rand = "0.8.5"
na = { package = "nalgebra", version = "0.32.1" }